<link rel="stylesheet" type="text/css" href="../css/metro-bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="../css/metro-bootstrap-responsive.min.css">
<link rel="stylesheet" type="text/css" href="../css/iconFont.min.css">
<link rel="stylesheet" type="text/css" href="../css/styles.css">

<script type="text/javascript" src="../js/jquery.js"></script>
<script type="text/javascript" src="../js/jquery.widget.min.js"></script>
<script type="text/javascript" src="../js/metro.min.js"></script>
<script type="text/javascript" src="../js/metro-live-tile.js"></script>
<script type="text/javascript" src="../js/codigo.js"></script>